### ISSUE TITLE
Install instructions still refer to the shimt/pam-exec-oauth2 which is not maintained

### ISSUE THREAD

**Issue by ciresnave** [metal-stack/pam-exec-oauth2#14]
Since this fork of pam-exec-oauth2 is moving forward and shimt/pam-exec-oauth2 is no longer maintained, shouldn't the install documentation in the readme file refer to this fork as well?  Is there a reason not to?

**Comment by majst01** [comment]
fixed with: https://github.com/metal-stack/pam-exec-oauth2/pull/15

**Comment by ciresnave** [comment]
Thank you.
